

services:
  frontend:
    build:
      context: ./my-app
      dockerfile: Dockerfile
    image: myapp:latest
    container_name: myapp_frontend
    ports:
      - "3000:80"  # Truy cập frontend tại http://localhost:3000
    depends_on:
      - backend

  backend:
    build:
      context: ./todo_api
      dockerfile: Dockerfile
    image: todoapi:latest
    container_name: myapp_backend
    ports:
      - "8080:8080"  # API chạy ở http://localhost:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
