apiVersion : apps/v1
kind: Deployment
metadata:
  name: dtbinhtodolist 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dtbinhtodolist
  template:
    metadata:
      labels:
        app: dtbinhtodolist 
    spec:
      containers:
        - name: dtbinhtodolist 
          image: reggistrytodo.azurecr.io/dtbinhtodolist
          ports:
          - containerPort: 80